<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Authzed\Api\V1;

/**
 * Protobuf enum <code>authzed.api.v1.AlgebraicSubjectSet.Operation</code>
 */
class AlgebraicSubjectSet_Operation
{
    /**
     * <code>OPERATION_UNSPECIFIED = 0;</code>
     */
    const OPERATION_UNSPECIFIED = 0;
    /**
     * <code>OPERATION_UNION = 1;</code>
     */
    const OPERATION_UNION = 1;
    /**
     * <code>OPERATION_INTERSECTION = 2;</code>
     */
    const OPERATION_INTERSECTION = 2;
    /**
     * <code>OPERATION_EXCLUSION = 3;</code>
     */
    const OPERATION_EXCLUSION = 3;
}

