<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug.proto

namespace Authzed\Api\V1;

/**
 * Protobuf enum <code>authzed.api.v1.CheckDebugTrace.PermissionType</code>
 */
class CheckDebugTrace_PermissionType
{
    /**
     * <code>PERMISSION_TYPE_UNSPECIFIED = 0;</code>
     */
    const PERMISSION_TYPE_UNSPECIFIED = 0;
    /**
     * <code>PERMISSION_TYPE_RELATION = 1;</code>
     */
    const PERMISSION_TYPE_RELATION = 1;
    /**
     * <code>PERMISSION_TYPE_PERMISSION = 2;</code>
     */
    const PERMISSION_TYPE_PERMISSION = 2;
}

