<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>authzed.api.v1.CheckPermissionResponse</code>
 */
class CheckPermissionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.authzed.api.v1.ZedToken checked_at = 1;</code>
     */
    private $checked_at = null;
    /**
     * <pre>
     * Permissionship communicates whether or not the subject has the requested
     * permission or has a relationship with the given resource, over the given
     * relation.
     * This value will be authzed.api.v1.PERMISSIONSHIP_HAS_PERMISSION if the
     * requested subject is a member of the computed permission set or there
     * exists a relationship with the requested relation from the given resource
     * to the given subject.
     * </pre>
     *
     * <code>.authzed.api.v1.CheckPermissionResponse.Permissionship permissionship = 2;</code>
     */
    private $permissionship = 0;

    public function __construct() {
        \GPBMetadata\PermissionService::initOnce();
        parent::__construct();
    }

    /**
     * <code>.authzed.api.v1.ZedToken checked_at = 1;</code>
     */
    public function getCheckedAt()
    {
        return $this->checked_at;
    }

    /**
     * <code>.authzed.api.v1.ZedToken checked_at = 1;</code>
     */
    public function setCheckedAt(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ZedToken::class);
        $this->checked_at = $var;
    }

    /**
     * <pre>
     * Permissionship communicates whether or not the subject has the requested
     * permission or has a relationship with the given resource, over the given
     * relation.
     * This value will be authzed.api.v1.PERMISSIONSHIP_HAS_PERMISSION if the
     * requested subject is a member of the computed permission set or there
     * exists a relationship with the requested relation from the given resource
     * to the given subject.
     * </pre>
     *
     * <code>.authzed.api.v1.CheckPermissionResponse.Permissionship permissionship = 2;</code>
     */
    public function getPermissionship()
    {
        return $this->permissionship;
    }

    /**
     * <pre>
     * Permissionship communicates whether or not the subject has the requested
     * permission or has a relationship with the given resource, over the given
     * relation.
     * This value will be authzed.api.v1.PERMISSIONSHIP_HAS_PERMISSION if the
     * requested subject is a member of the computed permission set or there
     * exists a relationship with the requested relation from the given resource
     * to the given subject.
     * </pre>
     *
     * <code>.authzed.api.v1.CheckPermissionResponse.Permissionship permissionship = 2;</code>
     */
    public function setPermissionship($var)
    {
        GPBUtil::checkEnum($var, \Authzed\Api\V1\CheckPermissionResponse_Permissionship::class);
        $this->permissionship = $var;
    }

}

