<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>authzed.api.v1.CheckDebugTrace.SubProblems</code>
 */
class CheckDebugTrace_SubProblems extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .authzed.api.v1.CheckDebugTrace traces = 1;</code>
     */
    private $traces;

    public function __construct() {
        \GPBMetadata\Debug::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .authzed.api.v1.CheckDebugTrace traces = 1;</code>
     */
    public function getTraces()
    {
        return $this->traces;
    }

    /**
     * <code>repeated .authzed.api.v1.CheckDebugTrace traces = 1;</code>
     */
    public function setTraces(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Authzed\Api\V1\CheckDebugTrace::class);
        $this->traces = $var;
    }

}

