<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

/**
 * Protobuf enum <code>authzed.api.v1.CheckPermissionResponse.Permissionship</code>
 */
class CheckPermissionResponse_Permissionship
{
    /**
     * <code>PERMISSIONSHIP_UNSPECIFIED = 0;</code>
     */
    const PERMISSIONSHIP_UNSPECIFIED = 0;
    /**
     * <code>PERMISSIONSHIP_NO_PERMISSION = 1;</code>
     */
    const PERMISSIONSHIP_NO_PERMISSION = 1;
    /**
     * <code>PERMISSIONSHIP_HAS_PERMISSION = 2;</code>
     */
    const PERMISSIONSHIP_HAS_PERMISSION = 2;
}

