<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>authzed.api.v1.DeleteRelationshipsResponse</code>
 */
class DeleteRelationshipsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.authzed.api.v1.ZedToken deleted_at = 1;</code>
     */
    private $deleted_at = null;

    public function __construct() {
        \GPBMetadata\PermissionService::initOnce();
        parent::__construct();
    }

    /**
     * <code>.authzed.api.v1.ZedToken deleted_at = 1;</code>
     */
    public function getDeletedAt()
    {
        return $this->deleted_at;
    }

    /**
     * <code>.authzed.api.v1.ZedToken deleted_at = 1;</code>
     */
    public function setDeletedAt(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ZedToken::class);
        $this->deleted_at = $var;
    }

}

