<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * DeleteRelationshipsRequest specifies which Relationships should be deleted,
 * requesting the delete of *ALL* relationships that match the specified
 * filters. If the optional_preconditions parameter is included, all of the
 * specified preconditions must also be satisfied before the delete will be
 * executed.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.DeleteRelationshipsRequest</code>
 */
class DeleteRelationshipsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 1 [(.validate.rules) = {</code>
     */
    private $relationship_filter = null;
    /**
     * <pre>
     * To be bounded by configuration
     * </pre>
     *
     * <code>repeated .authzed.api.v1.Precondition optional_preconditions = 2 [(.validate.rules) = {</code>
     */
    private $optional_preconditions;

    public function __construct() {
        \GPBMetadata\PermissionService::initOnce();
        parent::__construct();
    }

    /**
     * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 1 [(.validate.rules) = {</code>
     */
    public function getRelationshipFilter()
    {
        return $this->relationship_filter;
    }

    /**
     * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 1 [(.validate.rules) = {</code>
     */
    public function setRelationshipFilter(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\RelationshipFilter::class);
        $this->relationship_filter = $var;
    }

    /**
     * <pre>
     * To be bounded by configuration
     * </pre>
     *
     * <code>repeated .authzed.api.v1.Precondition optional_preconditions = 2 [(.validate.rules) = {</code>
     */
    public function getOptionalPreconditions()
    {
        return $this->optional_preconditions;
    }

    /**
     * <pre>
     * To be bounded by configuration
     * </pre>
     *
     * <code>repeated .authzed.api.v1.Precondition optional_preconditions = 2 [(.validate.rules) = {</code>
     */
    public function setOptionalPreconditions(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Authzed\Api\V1\Precondition::class);
        $this->optional_preconditions = $var;
    }

}

