<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ExpandPermissionTreeRequest returns a tree representing the expansion of all
 * relationships found accessible from a permission or relation on a particular
 * resource.
 * ExpandPermissionTreeRequest is typically used to determine the full set of
 * subjects with a permission, along with the relationships that grant said
 * access.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.ExpandPermissionTreeRequest</code>
 */
class ExpandPermissionTreeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     */
    private $consistency = null;
    /**
     * <pre>
     * resource is the resource over which to run the expansion.
     * </pre>
     *
     * <code>.authzed.api.v1.ObjectReference resource = 2 [(.validate.rules) = {</code>
     */
    private $resource = null;
    /**
     * <pre>
     * permission is the name of the permission or relation over which to run the
     * expansion for the resource.
     * </pre>
     *
     * <code>string permission = 3 [(.validate.rules) = {</code>
     */
    private $permission = '';

    public function __construct() {
        \GPBMetadata\PermissionService::initOnce();
        parent::__construct();
    }

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     */
    public function getConsistency()
    {
        return $this->consistency;
    }

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     */
    public function setConsistency(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\Consistency::class);
        $this->consistency = $var;
    }

    /**
     * <pre>
     * resource is the resource over which to run the expansion.
     * </pre>
     *
     * <code>.authzed.api.v1.ObjectReference resource = 2 [(.validate.rules) = {</code>
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * <pre>
     * resource is the resource over which to run the expansion.
     * </pre>
     *
     * <code>.authzed.api.v1.ObjectReference resource = 2 [(.validate.rules) = {</code>
     */
    public function setResource(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ObjectReference::class);
        $this->resource = $var;
    }

    /**
     * <pre>
     * permission is the name of the permission or relation over which to run the
     * expansion for the resource.
     * </pre>
     *
     * <code>string permission = 3 [(.validate.rules) = {</code>
     */
    public function getPermission()
    {
        return $this->permission;
    }

    /**
     * <pre>
     * permission is the name of the permission or relation over which to run the
     * expansion for the resource.
     * </pre>
     *
     * <code>string permission = 3 [(.validate.rules) = {</code>
     */
    public function setPermission($var)
    {
        GPBUtil::checkString($var, True);
        $this->permission = $var;
    }

}

