<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>authzed.api.v1.ExpandPermissionTreeResponse</code>
 */
class ExpandPermissionTreeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.authzed.api.v1.ZedToken expanded_at = 1;</code>
     */
    private $expanded_at = null;
    /**
     * <pre>
     * tree_root is a tree structure whose leaf nodes are subjects, and
     * intermediate nodes represent the various operations (union, intersection,
     * exclusion) to reach those subjects.
     * </pre>
     *
     * <code>.authzed.api.v1.PermissionRelationshipTree tree_root = 2;</code>
     */
    private $tree_root = null;

    public function __construct() {
        \GPBMetadata\PermissionService::initOnce();
        parent::__construct();
    }

    /**
     * <code>.authzed.api.v1.ZedToken expanded_at = 1;</code>
     */
    public function getExpandedAt()
    {
        return $this->expanded_at;
    }

    /**
     * <code>.authzed.api.v1.ZedToken expanded_at = 1;</code>
     */
    public function setExpandedAt(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ZedToken::class);
        $this->expanded_at = $var;
    }

    /**
     * <pre>
     * tree_root is a tree structure whose leaf nodes are subjects, and
     * intermediate nodes represent the various operations (union, intersection,
     * exclusion) to reach those subjects.
     * </pre>
     *
     * <code>.authzed.api.v1.PermissionRelationshipTree tree_root = 2;</code>
     */
    public function getTreeRoot()
    {
        return $this->tree_root;
    }

    /**
     * <pre>
     * tree_root is a tree structure whose leaf nodes are subjects, and
     * intermediate nodes represent the various operations (union, intersection,
     * exclusion) to reach those subjects.
     * </pre>
     *
     * <code>.authzed.api.v1.PermissionRelationshipTree tree_root = 2;</code>
     */
    public function setTreeRoot(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\PermissionRelationshipTree::class);
        $this->tree_root = $var;
    }

}

