<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * LookupResourcesResponse contains a single matching resource object ID for the
 * requested object type, permission, and subject.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.LookupResourcesResponse</code>
 */
class LookupResourcesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.authzed.api.v1.ZedToken looked_up_at = 1;</code>
     */
    private $looked_up_at = null;
    /**
     * <code>string resource_object_id = 2;</code>
     */
    private $resource_object_id = '';

    public function __construct() {
        \GPBMetadata\PermissionService::initOnce();
        parent::__construct();
    }

    /**
     * <code>.authzed.api.v1.ZedToken looked_up_at = 1;</code>
     */
    public function getLookedUpAt()
    {
        return $this->looked_up_at;
    }

    /**
     * <code>.authzed.api.v1.ZedToken looked_up_at = 1;</code>
     */
    public function setLookedUpAt(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ZedToken::class);
        $this->looked_up_at = $var;
    }

    /**
     * <code>string resource_object_id = 2;</code>
     */
    public function getResourceObjectId()
    {
        return $this->resource_object_id;
    }

    /**
     * <code>string resource_object_id = 2;</code>
     */
    public function setResourceObjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource_object_id = $var;
    }

}

