<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * LookupSubjectsResponse contains a single matching subject object ID for the
 * requested subject object type on the permission or relation.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.LookupSubjectsResponse</code>
 */
class LookupSubjectsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.authzed.api.v1.ZedToken looked_up_at = 1;</code>
     */
    private $looked_up_at = null;
    /**
     * <pre>
     * subject_object_id is the Object ID of the subject found. May be a `*` if
     * a wildcard was found.
     * </pre>
     *
     * <code>string subject_object_id = 2;</code>
     */
    private $subject_object_id = '';
    /**
     * <pre>
     * excluded_subject_ids are the Object IDs of the subjects excluded. This list
     * will only contain object IDs if `subject_object_id` is a wildcard (`*`) and
     * will only be populated if exclusions exist from the wildcard.
     * </pre>
     *
     * <code>repeated string excluded_subject_ids = 3;</code>
     */
    private $excluded_subject_ids;

    public function __construct() {
        \GPBMetadata\PermissionService::initOnce();
        parent::__construct();
    }

    /**
     * <code>.authzed.api.v1.ZedToken looked_up_at = 1;</code>
     */
    public function getLookedUpAt()
    {
        return $this->looked_up_at;
    }

    /**
     * <code>.authzed.api.v1.ZedToken looked_up_at = 1;</code>
     */
    public function setLookedUpAt(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ZedToken::class);
        $this->looked_up_at = $var;
    }

    /**
     * <pre>
     * subject_object_id is the Object ID of the subject found. May be a `*` if
     * a wildcard was found.
     * </pre>
     *
     * <code>string subject_object_id = 2;</code>
     */
    public function getSubjectObjectId()
    {
        return $this->subject_object_id;
    }

    /**
     * <pre>
     * subject_object_id is the Object ID of the subject found. May be a `*` if
     * a wildcard was found.
     * </pre>
     *
     * <code>string subject_object_id = 2;</code>
     */
    public function setSubjectObjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject_object_id = $var;
    }

    /**
     * <pre>
     * excluded_subject_ids are the Object IDs of the subjects excluded. This list
     * will only contain object IDs if `subject_object_id` is a wildcard (`*`) and
     * will only be populated if exclusions exist from the wildcard.
     * </pre>
     *
     * <code>repeated string excluded_subject_ids = 3;</code>
     */
    public function getExcludedSubjectIds()
    {
        return $this->excluded_subject_ids;
    }

    /**
     * <pre>
     * excluded_subject_ids are the Object IDs of the subjects excluded. This list
     * will only contain object IDs if `subject_object_id` is a wildcard (`*`) and
     * will only be populated if exclusions exist from the wildcard.
     * </pre>
     *
     * <code>repeated string excluded_subject_ids = 3;</code>
     */
    public function setExcludedSubjectIds(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->excluded_subject_ids = $var;
    }

}

