<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * PermissionRelationshipTree is used for representing a tree of a resource and
 * its permission relationships with other objects.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.PermissionRelationshipTree</code>
 */
class PermissionRelationshipTree extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.authzed.api.v1.ObjectReference expanded_object = 3;</code>
     */
    private $expanded_object = null;
    /**
     * <code>string expanded_relation = 4;</code>
     */
    private $expanded_relation = '';
    protected $tree_type;

    public function __construct() {
        \GPBMetadata\Core::initOnce();
        parent::__construct();
    }

    /**
     * <code>.authzed.api.v1.AlgebraicSubjectSet intermediate = 1;</code>
     */
    public function getIntermediate()
    {
        return $this->readOneof(1);
    }

    /**
     * <code>.authzed.api.v1.AlgebraicSubjectSet intermediate = 1;</code>
     */
    public function setIntermediate(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\AlgebraicSubjectSet::class);
        $this->writeOneof(1, $var);
    }

    /**
     * <code>.authzed.api.v1.DirectSubjectSet leaf = 2;</code>
     */
    public function getLeaf()
    {
        return $this->readOneof(2);
    }

    /**
     * <code>.authzed.api.v1.DirectSubjectSet leaf = 2;</code>
     */
    public function setLeaf(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\DirectSubjectSet::class);
        $this->writeOneof(2, $var);
    }

    /**
     * <code>.authzed.api.v1.ObjectReference expanded_object = 3;</code>
     */
    public function getExpandedObject()
    {
        return $this->expanded_object;
    }

    /**
     * <code>.authzed.api.v1.ObjectReference expanded_object = 3;</code>
     */
    public function setExpandedObject(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ObjectReference::class);
        $this->expanded_object = $var;
    }

    /**
     * <code>string expanded_relation = 4;</code>
     */
    public function getExpandedRelation()
    {
        return $this->expanded_relation;
    }

    /**
     * <code>string expanded_relation = 4;</code>
     */
    public function setExpandedRelation($var)
    {
        GPBUtil::checkString($var, True);
        $this->expanded_relation = $var;
    }

    public function getTreeType()
    {
        return $this->tree_type;
    }

}

