<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

/**
 * Protobuf enum <code>authzed.api.v1.Precondition.Operation</code>
 */
class Precondition_Operation
{
    /**
     * <code>OPERATION_UNSPECIFIED = 0;</code>
     */
    const OPERATION_UNSPECIFIED = 0;
    /**
     * <code>OPERATION_MUST_NOT_MATCH = 1;</code>
     */
    const OPERATION_MUST_NOT_MATCH = 1;
    /**
     * <code>OPERATION_MUST_MATCH = 2;</code>
     */
    const OPERATION_MUST_MATCH = 2;
}

