<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ReadSchemaResponse is the resulting data after having read the Object
 * Definitions from a Schema.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.ReadSchemaResponse</code>
 */
class ReadSchemaResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * schema_text is the textual form of the current schema in the system
     * </pre>
     *
     * <code>string schema_text = 1;</code>
     */
    private $schema_text = '';

    public function __construct() {
        \GPBMetadata\SchemaService::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * schema_text is the textual form of the current schema in the system
     * </pre>
     *
     * <code>string schema_text = 1;</code>
     */
    public function getSchemaText()
    {
        return $this->schema_text;
    }

    /**
     * <pre>
     * schema_text is the textual form of the current schema in the system
     * </pre>
     *
     * <code>string schema_text = 1;</code>
     */
    public function setSchemaText($var)
    {
        GPBUtil::checkString($var, True);
        $this->schema_text = $var;
    }

}

