<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ReadRelationshipsRequest specifies one or more filters used to read matching
 * relationships within the system.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.ReadRelationshipsRequest</code>
 */
class ReadRelationshipsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     */
    private $consistency = null;
    /**
     * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [(.validate.rules) = {</code>
     */
    private $relationship_filter = null;

    public function __construct() {
        \GPBMetadata\PermissionService::initOnce();
        parent::__construct();
    }

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     */
    public function getConsistency()
    {
        return $this->consistency;
    }

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     */
    public function setConsistency(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\Consistency::class);
        $this->consistency = $var;
    }

    /**
     * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [(.validate.rules) = {</code>
     */
    public function getRelationshipFilter()
    {
        return $this->relationship_filter;
    }

    /**
     * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [(.validate.rules) = {</code>
     */
    public function setRelationshipFilter(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\RelationshipFilter::class);
        $this->relationship_filter = $var;
    }

}

