<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ReadRelationshipsResponse contains a Relationship found that matches the
 * specified relationship filter(s). A instance of this response message will
 * be streamed to the client for each relationship found.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.ReadRelationshipsResponse</code>
 */
class ReadRelationshipsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.authzed.api.v1.ZedToken read_at = 1;</code>
     */
    private $read_at = null;
    /**
     * <code>.authzed.api.v1.Relationship relationship = 2;</code>
     */
    private $relationship = null;

    public function __construct() {
        \GPBMetadata\PermissionService::initOnce();
        parent::__construct();
    }

    /**
     * <code>.authzed.api.v1.ZedToken read_at = 1;</code>
     */
    public function getReadAt()
    {
        return $this->read_at;
    }

    /**
     * <code>.authzed.api.v1.ZedToken read_at = 1;</code>
     */
    public function setReadAt(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ZedToken::class);
        $this->read_at = $var;
    }

    /**
     * <code>.authzed.api.v1.Relationship relationship = 2;</code>
     */
    public function getRelationship()
    {
        return $this->relationship;
    }

    /**
     * <code>.authzed.api.v1.Relationship relationship = 2;</code>
     */
    public function setRelationship(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\Relationship::class);
        $this->relationship = $var;
    }

}

