<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ReadSchemaRequest returns the schema from the database.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.ReadSchemaRequest</code>
 */
class ReadSchemaRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\SchemaService::initOnce();
        parent::__construct();
    }

}

