<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * RelationshipUpdate is used for mutating a single relationship within the
 * service.
 * CREATE will create the relationship only if it doesn't exist, and error
 * otherwise.
 * TOUCH will upsert the relationship, and will not error if it
 * already exists.
 * DELETE will delete the relationship and error if it doesn't
 * exist.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.RelationshipUpdate</code>
 */
class RelationshipUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.authzed.api.v1.RelationshipUpdate.Operation operation = 1 [(.validate.rules) = {</code>
     */
    private $operation = 0;
    /**
     * <code>.authzed.api.v1.Relationship relationship = 2 [(.validate.rules) = {</code>
     */
    private $relationship = null;

    public function __construct() {
        \GPBMetadata\Core::initOnce();
        parent::__construct();
    }

    /**
     * <code>.authzed.api.v1.RelationshipUpdate.Operation operation = 1 [(.validate.rules) = {</code>
     */
    public function getOperation()
    {
        return $this->operation;
    }

    /**
     * <code>.authzed.api.v1.RelationshipUpdate.Operation operation = 1 [(.validate.rules) = {</code>
     */
    public function setOperation($var)
    {
        GPBUtil::checkEnum($var, \Authzed\Api\V1\RelationshipUpdate_Operation::class);
        $this->operation = $var;
    }

    /**
     * <code>.authzed.api.v1.Relationship relationship = 2 [(.validate.rules) = {</code>
     */
    public function getRelationship()
    {
        return $this->relationship;
    }

    /**
     * <code>.authzed.api.v1.Relationship relationship = 2 [(.validate.rules) = {</code>
     */
    public function setRelationship(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\Relationship::class);
        $this->relationship = $var;
    }

}

