<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Authzed\Api\V1;

/**
 * Protobuf enum <code>authzed.api.v1.RelationshipUpdate.Operation</code>
 */
class RelationshipUpdate_Operation
{
    /**
     * <code>OPERATION_UNSPECIFIED = 0;</code>
     */
    const OPERATION_UNSPECIFIED = 0;
    /**
     * <code>OPERATION_CREATE = 1;</code>
     */
    const OPERATION_CREATE = 1;
    /**
     * <code>OPERATION_TOUCH = 2;</code>
     */
    const OPERATION_TOUCH = 2;
    /**
     * <code>OPERATION_DELETE = 3;</code>
     */
    const OPERATION_DELETE = 3;
}

