<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Relationship specifies how a resource relates to a subject. Relationships
 * form the data for the graph over which all permissions questions are
 * answered.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.Relationship</code>
 */
class Relationship extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * resource is the resource to which the subject is related, in some manner
     * </pre>
     *
     * <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = {</code>
     */
    private $resource = null;
    /**
     * <pre>
     * relation is how the resource and subject are related.
     * </pre>
     *
     * <code>string relation = 2 [(.validate.rules) = {</code>
     */
    private $relation = '';
    /**
     * <pre>
     * subject is the subject to which the resource is related, in some manner.
     * </pre>
     *
     * <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = {</code>
     */
    private $subject = null;

    public function __construct() {
        \GPBMetadata\Core::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * resource is the resource to which the subject is related, in some manner
     * </pre>
     *
     * <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = {</code>
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * <pre>
     * resource is the resource to which the subject is related, in some manner
     * </pre>
     *
     * <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = {</code>
     */
    public function setResource(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ObjectReference::class);
        $this->resource = $var;
    }

    /**
     * <pre>
     * relation is how the resource and subject are related.
     * </pre>
     *
     * <code>string relation = 2 [(.validate.rules) = {</code>
     */
    public function getRelation()
    {
        return $this->relation;
    }

    /**
     * <pre>
     * relation is how the resource and subject are related.
     * </pre>
     *
     * <code>string relation = 2 [(.validate.rules) = {</code>
     */
    public function setRelation($var)
    {
        GPBUtil::checkString($var, True);
        $this->relation = $var;
    }

    /**
     * <pre>
     * subject is the subject to which the resource is related, in some manner.
     * </pre>
     *
     * <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = {</code>
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * <pre>
     * subject is the subject to which the resource is related, in some manner.
     * </pre>
     *
     * <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = {</code>
     */
    public function setSubject(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\SubjectReference::class);
        $this->subject = $var;
    }

}

