<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>authzed.api.v1.SubjectFilter.RelationFilter</code>
 */
class SubjectFilter_RelationFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string relation = 1 [(.validate.rules) = {</code>
     */
    private $relation = '';

    public function __construct() {
        \GPBMetadata\PermissionService::initOnce();
        parent::__construct();
    }

    /**
     * <code>string relation = 1 [(.validate.rules) = {</code>
     */
    public function getRelation()
    {
        return $this->relation;
    }

    /**
     * <code>string relation = 1 [(.validate.rules) = {</code>
     */
    public function setRelation($var)
    {
        GPBUtil::checkString($var, True);
        $this->relation = $var;
    }

}

