<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * SubjectFilter specifies a filter on the subject of a relationship.
 * subject_type is required and all other fields are optional, and will not
 * impose any additional requirements if left unspecified.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.SubjectFilter</code>
 */
class SubjectFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string subject_type = 1 [(.validate.rules) = {</code>
     */
    private $subject_type = '';
    /**
     * <code>string optional_subject_id = 2 [(.validate.rules) = {</code>
     */
    private $optional_subject_id = '';
    /**
     * <code>.authzed.api.v1.SubjectFilter.RelationFilter optional_relation = 3;</code>
     */
    private $optional_relation = null;

    public function __construct() {
        \GPBMetadata\PermissionService::initOnce();
        parent::__construct();
    }

    /**
     * <code>string subject_type = 1 [(.validate.rules) = {</code>
     */
    public function getSubjectType()
    {
        return $this->subject_type;
    }

    /**
     * <code>string subject_type = 1 [(.validate.rules) = {</code>
     */
    public function setSubjectType($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject_type = $var;
    }

    /**
     * <code>string optional_subject_id = 2 [(.validate.rules) = {</code>
     */
    public function getOptionalSubjectId()
    {
        return $this->optional_subject_id;
    }

    /**
     * <code>string optional_subject_id = 2 [(.validate.rules) = {</code>
     */
    public function setOptionalSubjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->optional_subject_id = $var;
    }

    /**
     * <code>.authzed.api.v1.SubjectFilter.RelationFilter optional_relation = 3;</code>
     */
    public function getOptionalRelation()
    {
        return $this->optional_relation;
    }

    /**
     * <code>.authzed.api.v1.SubjectFilter.RelationFilter optional_relation = 3;</code>
     */
    public function setOptionalRelation(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\SubjectFilter_RelationFilter::class);
        $this->optional_relation = $var;
    }

}

