<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * SubjectReference is used for referring to the subject portion of a
 * Relationship. The relation component is optional and is used for defining a
 * sub-relation on the subject, e.g. group:123#members
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.SubjectReference</code>
 */
class SubjectReference extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.authzed.api.v1.ObjectReference object = 1 [(.validate.rules) = {</code>
     */
    private $object = null;
    /**
     * <code>string optional_relation = 2 [(.validate.rules) = {</code>
     */
    private $optional_relation = '';

    public function __construct() {
        \GPBMetadata\Core::initOnce();
        parent::__construct();
    }

    /**
     * <code>.authzed.api.v1.ObjectReference object = 1 [(.validate.rules) = {</code>
     */
    public function getObject()
    {
        return $this->object;
    }

    /**
     * <code>.authzed.api.v1.ObjectReference object = 1 [(.validate.rules) = {</code>
     */
    public function setObject(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ObjectReference::class);
        $this->object = $var;
    }

    /**
     * <code>string optional_relation = 2 [(.validate.rules) = {</code>
     */
    public function getOptionalRelation()
    {
        return $this->optional_relation;
    }

    /**
     * <code>string optional_relation = 2 [(.validate.rules) = {</code>
     */
    public function setOptionalRelation($var)
    {
        GPBUtil::checkString($var, True);
        $this->optional_relation = $var;
    }

}

