<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watch_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * WatchRequest specifies the object definitions for which we want to start
 * watching mutations, and an optional start snapshot for when to start
 * watching.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.WatchRequest</code>
 */
class WatchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated string optional_object_types = 1 [(.validate.rules) = {</code>
     */
    private $optional_object_types;
    /**
     * <code>.authzed.api.v1.ZedToken optional_start_cursor = 2;</code>
     */
    private $optional_start_cursor = null;

    public function __construct() {
        \GPBMetadata\WatchService::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated string optional_object_types = 1 [(.validate.rules) = {</code>
     */
    public function getOptionalObjectTypes()
    {
        return $this->optional_object_types;
    }

    /**
     * <code>repeated string optional_object_types = 1 [(.validate.rules) = {</code>
     */
    public function setOptionalObjectTypes(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->optional_object_types = $var;
    }

    /**
     * <code>.authzed.api.v1.ZedToken optional_start_cursor = 2;</code>
     */
    public function getOptionalStartCursor()
    {
        return $this->optional_start_cursor;
    }

    /**
     * <code>.authzed.api.v1.ZedToken optional_start_cursor = 2;</code>
     */
    public function setOptionalStartCursor(&$var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ZedToken::class);
        $this->optional_start_cursor = $var;
    }

}

