<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * WriteSchemaRequest is the required data used to "upsert" the Schema of a
 * Permissions System.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.WriteSchemaRequest</code>
 */
class WriteSchemaRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The Schema containing one or more Object Definitions that will be written
     * to the Permissions System.
     * </pre>
     *
     * <code>string schema = 1 [(.validate.rules) = {</code>
     */
    private $schema = '';

    public function __construct() {
        \GPBMetadata\SchemaService::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The Schema containing one or more Object Definitions that will be written
     * to the Permissions System.
     * </pre>
     *
     * <code>string schema = 1 [(.validate.rules) = {</code>
     */
    public function getSchema()
    {
        return $this->schema;
    }

    /**
     * <pre>
     * The Schema containing one or more Object Definitions that will be written
     * to the Permissions System.
     * </pre>
     *
     * <code>string schema = 1 [(.validate.rules) = {</code>
     */
    public function setSchema($var)
    {
        GPBUtil::checkString($var, True);
        $this->schema = $var;
    }

}

