<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * WriteRelationshipsRequest contains a list of Relationship mutations that
 * should be applied to the service. If the optional_preconditions parameter
 * is included, all of the specified preconditions must also be satisfied before
 * the write will be committed.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.WriteRelationshipsRequest</code>
 */
class WriteRelationshipsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .authzed.api.v1.RelationshipUpdate updates = 1 [(.validate.rules) = {</code>
     */
    private $updates;
    /**
     * <pre>
     * To be bounded by configuration
     * </pre>
     *
     * <code>repeated .authzed.api.v1.Precondition optional_preconditions = 2 [(.validate.rules) = {</code>
     */
    private $optional_preconditions;

    public function __construct() {
        \GPBMetadata\PermissionService::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .authzed.api.v1.RelationshipUpdate updates = 1 [(.validate.rules) = {</code>
     */
    public function getUpdates()
    {
        return $this->updates;
    }

    /**
     * <code>repeated .authzed.api.v1.RelationshipUpdate updates = 1 [(.validate.rules) = {</code>
     */
    public function setUpdates(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Authzed\Api\V1\RelationshipUpdate::class);
        $this->updates = $var;
    }

    /**
     * <pre>
     * To be bounded by configuration
     * </pre>
     *
     * <code>repeated .authzed.api.v1.Precondition optional_preconditions = 2 [(.validate.rules) = {</code>
     */
    public function getOptionalPreconditions()
    {
        return $this->optional_preconditions;
    }

    /**
     * <pre>
     * To be bounded by configuration
     * </pre>
     *
     * <code>repeated .authzed.api.v1.Precondition optional_preconditions = 2 [(.validate.rules) = {</code>
     */
    public function setOptionalPreconditions(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Authzed\Api\V1\Precondition::class);
        $this->optional_preconditions = $var;
    }

}

