<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ZedToken is used to provide causality metadata between Write and Check
 * requests.
 * See the authzed.api.v1.Consistency message for more information.
 * </pre>
 *
 * Protobuf type <code>authzed.api.v1.ZedToken</code>
 */
class ZedToken extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string token = 1 [(.validate.rules) = {</code>
     */
    private $token = '';

    public function __construct() {
        \GPBMetadata\Core::initOnce();
        parent::__construct();
    }

    /**
     * <code>string token = 1 [(.validate.rules) = {</code>
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * <code>string token = 1 [(.validate.rules) = {</code>
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;
    }

}

