<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/annotations.proto

namespace GPBMetadata\Google\Api;

class Annotations
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Http::initOnce();
        \GPBMetadata\Google\Protobuf\Internal\Descriptor::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa2020a1c676f6f676c652f6170692f616e6e6f746174696f6e732e7072" .
            "6f746f120a676f6f676c652e6170691a15676f6f676c652f6170692f6874" .
            "74702e70726f746f1a20676f6f676c652f70726f746f6275662f64657363" .
            "726970746f722e70726f746f3a450a0468747470121e2e676f6f676c652e" .
            "70726f746f6275662e4d6574686f644f7074696f6e7318b0cabc22200128" .
            "0b32142e676f6f676c652e6170692e4874747052756c65426e0a0e636f6d" .
            "2e676f6f676c652e6170694210416e6e6f746174696f6e7350726f746f50" .
            "015a41676f6f676c652e676f6c616e672e6f72672f67656e70726f746f2f" .
            "676f6f676c65617069732f6170692f616e6e6f746174696f6e733b616e6e" .
            "6f746174696f6e73a2020447415049620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

