<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc-gen-openapiv2/options/openapiv2.proto

namespace Grpc\Gateway\Protoc_gen_openapiv2\Options;

if (false) {
    /**
     * This class is deprecated. Use Grpc\Gateway\Protoc_gen_openapiv2\Options\JSONSchema\JSONSchemaSimpleTypes instead.
     * @deprecated
     */
    class JSONSchema_JSONSchemaSimpleTypes {}
}
class_exists(JSONSchema\JSONSchemaSimpleTypes::class);
@trigger_error('Grpc\Gateway\Protoc_gen_openapiv2\Options\JSONSchema_JSONSchemaSimpleTypes is deprecated and will be removed in the next major release. Use Grpc\Gateway\Protoc_gen_openapiv2\Options\JSONSchema\JSONSchemaSimpleTypes instead', E_USER_DEPRECATED);

