<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc-gen-openapiv2/options/openapiv2.proto

namespace Grpc\Gateway\Protoc_gen_openapiv2\Options;

if (false) {
    /**
     * This class is deprecated. Use Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityScheme\Flow instead.
     * @deprecated
     */
    class SecurityScheme_Flow {}
}
class_exists(SecurityScheme\Flow::class);
@trigger_error('Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityScheme_Flow is deprecated and will be removed in the next major release. Use Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityScheme\Flow instead', E_USER_DEPRECATED);

