<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc-gen-openapiv2/options/openapiv2.proto

namespace Grpc\Gateway\Protoc_gen_openapiv2\Options;

if (false) {
    /**
     * This class is deprecated. Use Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityScheme\Type instead.
     * @deprecated
     */
    class SecurityScheme_Type {}
}
class_exists(SecurityScheme\Type::class);
@trigger_error('Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityScheme_Type is deprecated and will be removed in the next major release. Use Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityScheme\Type instead', E_USER_DEPRECATED);

