<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc-gen-openapiv2/options/openapiv2.proto

namespace Grpc\Gateway\Protoc_gen_openapiv2\Options;

if (false) {
    /**
     * This class is deprecated. Use Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityScheme\In instead.
     * @deprecated
     */
    class SecurityScheme_In {}
}
class_exists(SecurityScheme\In::class);
@trigger_error('Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityScheme_In is deprecated and will be removed in the next major release. Use Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityScheme\In instead', E_USER_DEPRECATED);

