<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc-gen-openapiv2/options/openapiv2.proto

namespace Grpc\Gateway\Protoc_gen_openapiv2\Options;

if (false) {
    /**
     * This class is deprecated. Use Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityRequirement\SecurityRequirementValue instead.
     * @deprecated
     */
    class SecurityRequirement_SecurityRequirementValue {}
}
class_exists(SecurityRequirement\SecurityRequirementValue::class);
@trigger_error('Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityRequirement_SecurityRequirementValue is deprecated and will be removed in the next major release. Use Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityRequirement\SecurityRequirementValue instead', E_USER_DEPRECATED);

