<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi.proto

namespace GPBMetadata;

class Openapi
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ProtocGenOpenapiv2\Options\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
ª
openapi.protoauthzed.api.v1B€
com.authzed.api.v1Z2github.com/authzed/authzed-go/proto/authzed/api/v1’A´œ
Authzed"D
Authzed, Inc.https://github.com/authzed/apisupport@authzed.com*F
Apache 2.0 License0https://github.com/authzed/api/blob/main/LICENSE21.0*2application/json:application/jsonZ#
!

ApiKeyAuthAuthorization rE
More about the Authzed API.&https://docs.authzed.com/reference/apibproto3'
        , true);

        static::$is_initialized = true;
    }
}

