<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi.proto

namespace GPBMetadata;

class Openapi
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ProtocGenOpenapiv2\Options\Annotations::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ada030a0d6f70656e6170692e70726f746f120e617574687a65642e6170" .
            "692e76311a2e70726f746f632d67656e2d6f70656e61706976322f6f7074" .
            "696f6e732f616e6e6f746174696f6e732e70726f746f4280030a12636f6d" .
            "2e617574687a65642e6170692e76315a326769746875622e636f6d2f6175" .
            "74687a65642f617574687a65642d676f2f70726f746f2f617574687a6564" .
            "2f6170692f76319241b402129c010a07417574687a656422440a0d417574" .
            "687a65642c20496e632e121e68747470733a2f2f6769746875622e636f6d" .
            "2f617574687a65642f6170691a13737570706f727440617574687a65642e" .
            "636f6d2a460a1241706163686520322e30204c6963656e73651230687474" .
            "70733a2f2f6769746875622e636f6d2f617574687a65642f6170692f626c" .
            "6f622f6d61696e2f4c4943454e53453203312e302a030102043210617070" .
            "6c69636174696f6e2f6a736f6e3a106170706c69636174696f6e2f6a736f" .
            "6e5a230a210a0a4170694b657941757468121308021a0d417574686f7269" .
            "7a6174696f6e200272450a1b4d6f72652061626f75742074686520417574" .
            "687a6564204150492e122668747470733a2f2f646f63732e617574687a65" .
            "642e636f6d2f7265666572656e63652f617069620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

