<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Authzed\Api\V1;

if (false) {
    /**
     * This class is deprecated. Use Authzed\Api\V1\AlgebraicSubjectSet\Operation instead.
     * @deprecated
     */
    class AlgebraicSubjectSet_Operation {}
}
class_exists(AlgebraicSubjectSet\Operation::class);
@trigger_error('Authzed\Api\V1\AlgebraicSubjectSet_Operation is deprecated and will be removed in the next major release. Use Authzed\Api\V1\AlgebraicSubjectSet\Operation instead', E_USER_DEPRECATED);

