<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug.proto

namespace Authzed\Api\V1;

if (false) {
    /**
     * This class is deprecated. Use Authzed\Api\V1\CheckDebugTrace\Permissionship instead.
     * @deprecated
     */
    class CheckDebugTrace_Permissionship {}
}
class_exists(CheckDebugTrace\Permissionship::class);
@trigger_error('Authzed\Api\V1\CheckDebugTrace_Permissionship is deprecated and will be removed in the next major release. Use Authzed\Api\V1\CheckDebugTrace\Permissionship instead', E_USER_DEPRECATED);

