<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

if (false) {
    /**
     * This class is deprecated. Use Authzed\Api\V1\CheckPermissionResponse\Permissionship instead.
     * @deprecated
     */
    class CheckPermissionResponse_Permissionship {}
}
class_exists(CheckPermissionResponse\Permissionship::class);
@trigger_error('Authzed\Api\V1\CheckPermissionResponse_Permissionship is deprecated and will be removed in the next major release. Use Authzed\Api\V1\CheckPermissionResponse\Permissionship instead', E_USER_DEPRECATED);

