<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug.proto

namespace Authzed\Api\V1;

if (false) {
    /**
     * This class is deprecated. Use Authzed\Api\V1\CheckDebugTrace\PermissionType instead.
     * @deprecated
     */
    class CheckDebugTrace_PermissionType {}
}
class_exists(CheckDebugTrace\PermissionType::class);
@trigger_error('Authzed\Api\V1\CheckDebugTrace_PermissionType is deprecated and will be removed in the next major release. Use Authzed\Api\V1\CheckDebugTrace\PermissionType instead', E_USER_DEPRECATED);

