<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug.proto

namespace Authzed\Api\V1;

if (false) {
    /**
     * This class is deprecated. Use Authzed\Api\V1\CheckDebugTrace\SubProblems instead.
     * @deprecated
     */
    class CheckDebugTrace_SubProblems {}
}
class_exists(CheckDebugTrace\SubProblems::class);
@trigger_error('Authzed\Api\V1\CheckDebugTrace_SubProblems is deprecated and will be removed in the next major release. Use Authzed\Api\V1\CheckDebugTrace\SubProblems instead', E_USER_DEPRECATED);

