<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * DirectSubjectSet is a subject set which is simply a collection of subjects.
 *
 * Generated from protobuf message <code>authzed.api.v1.DirectSubjectSet</code>
 */
class DirectSubjectSet extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .authzed.api.v1.SubjectReference subjects = 1;</code>
     */
    private $subjects;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Authzed\Api\V1\SubjectReference>|\Google\Protobuf\Internal\RepeatedField $subjects
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .authzed.api.v1.SubjectReference subjects = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubjects()
    {
        return $this->subjects;
    }

    /**
     * Generated from protobuf field <code>repeated .authzed.api.v1.SubjectReference subjects = 1;</code>
     * @param array<\Authzed\Api\V1\SubjectReference>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubjects($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Authzed\Api\V1\SubjectReference::class);
        $this->subjects = $arr;

        return $this;
    }

}

