<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ObjectReference is used to refer to a specific object in the system.
 *
 * Generated from protobuf message <code>authzed.api.v1.ObjectReference</code>
 */
class ObjectReference extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string object_type = 1 [(.validate.rules) = {</code>
     */
    protected $object_type = '';
    /**
     * Generated from protobuf field <code>string object_id = 2 [(.validate.rules) = {</code>
     */
    protected $object_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $object_type
     *     @type string $object_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string object_type = 1 [(.validate.rules) = {</code>
     * @return string
     */
    public function getObjectType()
    {
        return $this->object_type;
    }

    /**
     * Generated from protobuf field <code>string object_type = 1 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setObjectType($var)
    {
        GPBUtil::checkString($var, True);
        $this->object_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string object_id = 2 [(.validate.rules) = {</code>
     * @return string
     */
    public function getObjectId()
    {
        return $this->object_id;
    }

    /**
     * Generated from protobuf field <code>string object_id = 2 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setObjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->object_id = $var;

        return $this;
    }

}

