<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

if (false) {
    /**
     * This class is deprecated. Use Authzed\Api\V1\Precondition\Operation instead.
     * @deprecated
     */
    class Precondition_Operation {}
}
class_exists(Precondition\Operation::class);
@trigger_error('Authzed\Api\V1\Precondition_Operation is deprecated and will be removed in the next major release. Use Authzed\Api\V1\Precondition\Operation instead', E_USER_DEPRECATED);

