<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Precondition specifies how and the existence or absence of certain
 * relationships as expressed through the accompanying filter should affect
 * whether or not the operation proceeds.
 * MUST_NOT_MATCH will fail the parent request if any relationships match the
 * relationships filter.
 * MUST_MATCH will fail the parent request if there are no
 * relationships that match the filter.
 *
 * Generated from protobuf message <code>authzed.api.v1.Precondition</code>
 */
class Precondition extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.authzed.api.v1.Precondition.Operation operation = 1 [(.validate.rules) = {</code>
     */
    protected $operation = 0;
    /**
     * Generated from protobuf field <code>.authzed.api.v1.RelationshipFilter filter = 2 [(.validate.rules) = {</code>
     */
    protected $filter = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $operation
     *     @type \Authzed\Api\V1\RelationshipFilter $filter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PermissionService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.Precondition.Operation operation = 1 [(.validate.rules) = {</code>
     * @return int
     */
    public function getOperation()
    {
        return $this->operation;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.Precondition.Operation operation = 1 [(.validate.rules) = {</code>
     * @param int $var
     * @return $this
     */
    public function setOperation($var)
    {
        GPBUtil::checkEnum($var, \Authzed\Api\V1\Precondition\Operation::class);
        $this->operation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.RelationshipFilter filter = 2 [(.validate.rules) = {</code>
     * @return \Authzed\Api\V1\RelationshipFilter|null
     */
    public function getFilter()
    {
        return $this->filter;
    }

    public function hasFilter()
    {
        return isset($this->filter);
    }

    public function clearFilter()
    {
        unset($this->filter);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.RelationshipFilter filter = 2 [(.validate.rules) = {</code>
     * @param \Authzed\Api\V1\RelationshipFilter $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\RelationshipFilter::class);
        $this->filter = $var;

        return $this;
    }

}

