<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Relationship specifies how a resource relates to a subject. Relationships
 * form the data for the graph over which all permissions questions are
 * answered.
 *
 * Generated from protobuf message <code>authzed.api.v1.Relationship</code>
 */
class Relationship extends \Google\Protobuf\Internal\Message
{
    /**
     * resource is the resource to which the subject is related, in some manner
     *
     * Generated from protobuf field <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = {</code>
     */
    protected $resource = null;
    /**
     * relation is how the resource and subject are related.
     *
     * Generated from protobuf field <code>string relation = 2 [(.validate.rules) = {</code>
     */
    protected $relation = '';
    /**
     * subject is the subject to which the resource is related, in some manner.
     *
     * Generated from protobuf field <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = {</code>
     */
    protected $subject = null;
    /**
     * optional_caveat is a reference to a the caveat that must be enforced over the relationship
     *
     * Generated from protobuf field <code>.authzed.api.v1.ContextualizedCaveat optional_caveat = 4 [(.validate.rules) = {</code>
     */
    protected $optional_caveat = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Authzed\Api\V1\ObjectReference $resource
     *           resource is the resource to which the subject is related, in some manner
     *     @type string $relation
     *           relation is how the resource and subject are related.
     *     @type \Authzed\Api\V1\SubjectReference $subject
     *           subject is the subject to which the resource is related, in some manner.
     *     @type \Authzed\Api\V1\ContextualizedCaveat $optional_caveat
     *           optional_caveat is a reference to a the caveat that must be enforced over the relationship
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * resource is the resource to which the subject is related, in some manner
     *
     * Generated from protobuf field <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = {</code>
     * @return \Authzed\Api\V1\ObjectReference|null
     */
    public function getResource()
    {
        return $this->resource;
    }

    public function hasResource()
    {
        return isset($this->resource);
    }

    public function clearResource()
    {
        unset($this->resource);
    }

    /**
     * resource is the resource to which the subject is related, in some manner
     *
     * Generated from protobuf field <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = {</code>
     * @param \Authzed\Api\V1\ObjectReference $var
     * @return $this
     */
    public function setResource($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ObjectReference::class);
        $this->resource = $var;

        return $this;
    }

    /**
     * relation is how the resource and subject are related.
     *
     * Generated from protobuf field <code>string relation = 2 [(.validate.rules) = {</code>
     * @return string
     */
    public function getRelation()
    {
        return $this->relation;
    }

    /**
     * relation is how the resource and subject are related.
     *
     * Generated from protobuf field <code>string relation = 2 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setRelation($var)
    {
        GPBUtil::checkString($var, True);
        $this->relation = $var;

        return $this;
    }

    /**
     * subject is the subject to which the resource is related, in some manner.
     *
     * Generated from protobuf field <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = {</code>
     * @return \Authzed\Api\V1\SubjectReference|null
     */
    public function getSubject()
    {
        return $this->subject;
    }

    public function hasSubject()
    {
        return isset($this->subject);
    }

    public function clearSubject()
    {
        unset($this->subject);
    }

    /**
     * subject is the subject to which the resource is related, in some manner.
     *
     * Generated from protobuf field <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = {</code>
     * @param \Authzed\Api\V1\SubjectReference $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\SubjectReference::class);
        $this->subject = $var;

        return $this;
    }

    /**
     * optional_caveat is a reference to a the caveat that must be enforced over the relationship
     *
     * Generated from protobuf field <code>.authzed.api.v1.ContextualizedCaveat optional_caveat = 4 [(.validate.rules) = {</code>
     * @return \Authzed\Api\V1\ContextualizedCaveat|null
     */
    public function getOptionalCaveat()
    {
        return $this->optional_caveat;
    }

    public function hasOptionalCaveat()
    {
        return isset($this->optional_caveat);
    }

    public function clearOptionalCaveat()
    {
        unset($this->optional_caveat);
    }

    /**
     * optional_caveat is a reference to a the caveat that must be enforced over the relationship
     *
     * Generated from protobuf field <code>.authzed.api.v1.ContextualizedCaveat optional_caveat = 4 [(.validate.rules) = {</code>
     * @param \Authzed\Api\V1\ContextualizedCaveat $var
     * @return $this
     */
    public function setOptionalCaveat($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ContextualizedCaveat::class);
        $this->optional_caveat = $var;

        return $this;
    }

}

