<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * RelationshipFilter is a collection of filters which when applied to a
 * relationship will return relationships that have exactly matching fields.
 * resource_type is required. All other fields are optional and if left
 * unspecified will not filter relationships.
 *
 * Generated from protobuf message <code>authzed.api.v1.RelationshipFilter</code>
 */
class RelationshipFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string resource_type = 1 [(.validate.rules) = {</code>
     */
    protected $resource_type = '';
    /**
     * Generated from protobuf field <code>string optional_resource_id = 2 [(.validate.rules) = {</code>
     */
    protected $optional_resource_id = '';
    /**
     * Generated from protobuf field <code>string optional_relation = 3 [(.validate.rules) = {</code>
     */
    protected $optional_relation = '';
    /**
     * Generated from protobuf field <code>.authzed.api.v1.SubjectFilter optional_subject_filter = 4;</code>
     */
    protected $optional_subject_filter = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $resource_type
     *     @type string $optional_resource_id
     *     @type string $optional_relation
     *     @type \Authzed\Api\V1\SubjectFilter $optional_subject_filter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PermissionService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string resource_type = 1 [(.validate.rules) = {</code>
     * @return string
     */
    public function getResourceType()
    {
        return $this->resource_type;
    }

    /**
     * Generated from protobuf field <code>string resource_type = 1 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setResourceType($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string optional_resource_id = 2 [(.validate.rules) = {</code>
     * @return string
     */
    public function getOptionalResourceId()
    {
        return $this->optional_resource_id;
    }

    /**
     * Generated from protobuf field <code>string optional_resource_id = 2 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setOptionalResourceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->optional_resource_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string optional_relation = 3 [(.validate.rules) = {</code>
     * @return string
     */
    public function getOptionalRelation()
    {
        return $this->optional_relation;
    }

    /**
     * Generated from protobuf field <code>string optional_relation = 3 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setOptionalRelation($var)
    {
        GPBUtil::checkString($var, True);
        $this->optional_relation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.SubjectFilter optional_subject_filter = 4;</code>
     * @return \Authzed\Api\V1\SubjectFilter|null
     */
    public function getOptionalSubjectFilter()
    {
        return $this->optional_subject_filter;
    }

    public function hasOptionalSubjectFilter()
    {
        return isset($this->optional_subject_filter);
    }

    public function clearOptionalSubjectFilter()
    {
        unset($this->optional_subject_filter);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.SubjectFilter optional_subject_filter = 4;</code>
     * @param \Authzed\Api\V1\SubjectFilter $var
     * @return $this
     */
    public function setOptionalSubjectFilter($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\SubjectFilter::class);
        $this->optional_subject_filter = $var;

        return $this;
    }

}

