<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Authzed\Api\V1;

if (false) {
    /**
     * This class is deprecated. Use Authzed\Api\V1\RelationshipUpdate\Operation instead.
     * @deprecated
     */
    class RelationshipUpdate_Operation {}
}
class_exists(RelationshipUpdate\Operation::class);
@trigger_error('Authzed\Api\V1\RelationshipUpdate_Operation is deprecated and will be removed in the next major release. Use Authzed\Api\V1\RelationshipUpdate\Operation instead', E_USER_DEPRECATED);

