<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * RelationshipUpdate is used for mutating a single relationship within the
 * service.
 * CREATE will create the relationship only if it doesn't exist, and error
 * otherwise.
 * TOUCH will upsert the relationship, and will not error if it
 * already exists.
 * DELETE will delete the relationship and error if it doesn't
 * exist.
 *
 * Generated from protobuf message <code>authzed.api.v1.RelationshipUpdate</code>
 */
class RelationshipUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.authzed.api.v1.RelationshipUpdate.Operation operation = 1 [(.validate.rules) = {</code>
     */
    protected $operation = 0;
    /**
     * Generated from protobuf field <code>.authzed.api.v1.Relationship relationship = 2 [(.validate.rules) = {</code>
     */
    protected $relationship = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $operation
     *     @type \Authzed\Api\V1\Relationship $relationship
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.RelationshipUpdate.Operation operation = 1 [(.validate.rules) = {</code>
     * @return int
     */
    public function getOperation()
    {
        return $this->operation;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.RelationshipUpdate.Operation operation = 1 [(.validate.rules) = {</code>
     * @param int $var
     * @return $this
     */
    public function setOperation($var)
    {
        GPBUtil::checkEnum($var, \Authzed\Api\V1\RelationshipUpdate\Operation::class);
        $this->operation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.Relationship relationship = 2 [(.validate.rules) = {</code>
     * @return \Authzed\Api\V1\Relationship|null
     */
    public function getRelationship()
    {
        return $this->relationship;
    }

    public function hasRelationship()
    {
        return isset($this->relationship);
    }

    public function clearRelationship()
    {
        unset($this->relationship);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.Relationship relationship = 2 [(.validate.rules) = {</code>
     * @param \Authzed\Api\V1\Relationship $var
     * @return $this
     */
    public function setRelationship($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\Relationship::class);
        $this->relationship = $var;

        return $this;
    }

}

