<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SubjectReference is used for referring to the subject portion of a
 * Relationship. The relation component is optional and is used for defining a
 * sub-relation on the subject, e.g. group:123#members
 *
 * Generated from protobuf message <code>authzed.api.v1.SubjectReference</code>
 */
class SubjectReference extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.authzed.api.v1.ObjectReference object = 1 [(.validate.rules) = {</code>
     */
    protected $object = null;
    /**
     * Generated from protobuf field <code>string optional_relation = 2 [(.validate.rules) = {</code>
     */
    protected $optional_relation = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Authzed\Api\V1\ObjectReference $object
     *     @type string $optional_relation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.ObjectReference object = 1 [(.validate.rules) = {</code>
     * @return \Authzed\Api\V1\ObjectReference|null
     */
    public function getObject()
    {
        return $this->object;
    }

    public function hasObject()
    {
        return isset($this->object);
    }

    public function clearObject()
    {
        unset($this->object);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.ObjectReference object = 1 [(.validate.rules) = {</code>
     * @param \Authzed\Api\V1\ObjectReference $var
     * @return $this
     */
    public function setObject($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ObjectReference::class);
        $this->object = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string optional_relation = 2 [(.validate.rules) = {</code>
     * @return string
     */
    public function getOptionalRelation()
    {
        return $this->optional_relation;
    }

    /**
     * Generated from protobuf field <code>string optional_relation = 2 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setOptionalRelation($var)
    {
        GPBUtil::checkString($var, True);
        $this->optional_relation = $var;

        return $this;
    }

}

