<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1;

if (false) {
    /**
     * This class is deprecated. Use Authzed\Api\V1\SubjectFilter\RelationFilter instead.
     * @deprecated
     */
    class SubjectFilter_RelationFilter {}
}
class_exists(SubjectFilter\RelationFilter::class);
@trigger_error('Authzed\Api\V1\SubjectFilter_RelationFilter is deprecated and will be removed in the next major release. Use Authzed\Api\V1\SubjectFilter\RelationFilter instead', E_USER_DEPRECATED);

