<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watch_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * WatchRequest specifies the object definitions for which we want to start
 * watching mutations, and an optional start snapshot for when to start
 * watching.
 *
 * Generated from protobuf message <code>authzed.api.v1.WatchRequest</code>
 */
class WatchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string optional_object_types = 1 [(.validate.rules) = {</code>
     */
    private $optional_object_types;
    /**
     * Generated from protobuf field <code>.authzed.api.v1.ZedToken optional_start_cursor = 2;</code>
     */
    protected $optional_start_cursor = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $optional_object_types
     *     @type \Authzed\Api\V1\ZedToken $optional_start_cursor
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\WatchService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string optional_object_types = 1 [(.validate.rules) = {</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOptionalObjectTypes()
    {
        return $this->optional_object_types;
    }

    /**
     * Generated from protobuf field <code>repeated string optional_object_types = 1 [(.validate.rules) = {</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOptionalObjectTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->optional_object_types = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.ZedToken optional_start_cursor = 2;</code>
     * @return \Authzed\Api\V1\ZedToken|null
     */
    public function getOptionalStartCursor()
    {
        return $this->optional_start_cursor;
    }

    public function hasOptionalStartCursor()
    {
        return isset($this->optional_start_cursor);
    }

    public function clearOptionalStartCursor()
    {
        unset($this->optional_start_cursor);
    }

    /**
     * Generated from protobuf field <code>.authzed.api.v1.ZedToken optional_start_cursor = 2;</code>
     * @param \Authzed\Api\V1\ZedToken $var
     * @return $this
     */
    public function setOptionalStartCursor($var)
    {
        GPBUtil::checkMessage($var, \Authzed\Api\V1\ZedToken::class);
        $this->optional_start_cursor = $var;

        return $this;
    }

}

