<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema_service.proto

namespace Authzed\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * WriteSchemaRequest is the required data used to "upsert" the Schema of a
 * Permissions System.
 *
 * Generated from protobuf message <code>authzed.api.v1.WriteSchemaRequest</code>
 */
class WriteSchemaRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The Schema containing one or more Object Definitions that will be written
     * to the Permissions System.
     *
     * Generated from protobuf field <code>string schema = 1 [(.validate.rules) = {</code>
     */
    protected $schema = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $schema
     *           The Schema containing one or more Object Definitions that will be written
     *           to the Permissions System.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SchemaService::initOnce();
        parent::__construct($data);
    }

    /**
     * The Schema containing one or more Object Definitions that will be written
     * to the Permissions System.
     *
     * Generated from protobuf field <code>string schema = 1 [(.validate.rules) = {</code>
     * @return string
     */
    public function getSchema()
    {
        return $this->schema;
    }

    /**
     * The Schema containing one or more Object Definitions that will be written
     * to the Permissions System.
     *
     * Generated from protobuf field <code>string schema = 1 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setSchema($var)
    {
        GPBUtil::checkString($var, True);
        $this->schema = $var;

        return $this;
    }

}

