<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission_service.proto

namespace Authzed\Api\V1\Precondition;

use UnexpectedValueException;

/**
 * Protobuf type <code>authzed.api.v1.Precondition.Operation</code>
 */
class Operation
{
    /**
     * Generated from protobuf enum <code>OPERATION_UNSPECIFIED = 0;</code>
     */
    const OPERATION_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>OPERATION_MUST_NOT_MATCH = 1;</code>
     */
    const OPERATION_MUST_NOT_MATCH = 1;
    /**
     * Generated from protobuf enum <code>OPERATION_MUST_MATCH = 2;</code>
     */
    const OPERATION_MUST_MATCH = 2;

    private static $valueToName = [
        self::OPERATION_UNSPECIFIED => 'OPERATION_UNSPECIFIED',
        self::OPERATION_MUST_NOT_MATCH => 'OPERATION_MUST_NOT_MATCH',
        self::OPERATION_MUST_MATCH => 'OPERATION_MUST_MATCH',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Operation::class, \Authzed\Api\V1\Precondition_Operation::class);

