<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Authzed\Api\V1\RelationshipUpdate;

use UnexpectedValueException;

/**
 * Protobuf type <code>authzed.api.v1.RelationshipUpdate.Operation</code>
 */
class Operation
{
    /**
     * Generated from protobuf enum <code>OPERATION_UNSPECIFIED = 0;</code>
     */
    const OPERATION_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>OPERATION_CREATE = 1;</code>
     */
    const OPERATION_CREATE = 1;
    /**
     * Generated from protobuf enum <code>OPERATION_TOUCH = 2;</code>
     */
    const OPERATION_TOUCH = 2;
    /**
     * Generated from protobuf enum <code>OPERATION_DELETE = 3;</code>
     */
    const OPERATION_DELETE = 3;

    private static $valueToName = [
        self::OPERATION_UNSPECIFIED => 'OPERATION_UNSPECIFIED',
        self::OPERATION_CREATE => 'OPERATION_CREATE',
        self::OPERATION_TOUCH => 'OPERATION_TOUCH',
        self::OPERATION_DELETE => 'OPERATION_DELETE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Operation::class, \Authzed\Api\V1\RelationshipUpdate_Operation::class);

